apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
spec:
  type: NodePort   # You can also use LoadBalancer if your cloud supports it
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80       # Cluster port
      targetPort: 80 # Pod port
      nodePort: 30080 # Accessible on your VM node
